---
include:
  - board: nice_nano_v2
    shield: microdox_left
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: microdox_right
